name: ARDaP_v1.5
channels:
  - conda-forge
  - bioconda
  - defaults
  - ursky
  - r
dependencies:
  - _libgcc_mutex=0.1=main
  - bwa=0.7.17=h84994c4_5
  - bzip2=1.0.8=h516909a_0
  - ca-certificates=2019.6.16=hecc5488_0
  - certifi=2019.6.16=py37_1
  - curl=7.65.3=hf8cf82a_0
  - htslib=1.9=ha228f0b_7
  - krb5=1.16.3=h05b26f9_1001
  - libcurl=7.65.3=hda55be3_0
  - libdeflate=1.0=h14c3975_1
  - libedit=3.1.20170329=hf8c457e_1001
  - libffi=3.2.1=he1b5a44_1006
  - libgcc-ng=9.1.0=hdf63c60_0
  - libssh2=1.8.2=h22169c7_2
  - libstdcxx-ng=9.1.0=hdf63c60_0
  - mosdepth=0.2.5=hb763d49_0
  - ncurses=6.1=hf484d3e_1002
  - openjdk=11.0.1=h516909a_1016
  - openssl=1.1.1c=h516909a_0
  - pcre=8.41=hf484d3e_1003
  - perl=5.26.2=h516909a_1006
  - pindel=0.2.5b9=he527e40_3
  - pip=19.1.1=py37_0
  - python=3.7.3=h33d41f4_1
  - readline=8.0=hf8c457e_0
  - samtools=1.9=h8571acd_11
  - seqtk=1.3=h84994c4_1
  - setuptools=41.0.1=py37_0
  - sqlite=3.29.0=hcee41ef_0
  - tk=8.6.9=hed695b0_1002
  - trimmomatic=0.39=1
  - wheel=0.33.4=py37_0
  - xz=5.2.4=h14c3975_1001
  - zlib=1.2.11=h516909a_1005
prefix: /home/dsarovich2/anaconda3/envs/ARDaP_v1.5
